<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KozLibraries.AutoRegisterAnnotation" PrivateAssets="all" />
    <PackageReference Include="KozLibraries.DapperDateOnlySupport" />
    <PackageReference Include="KozLibraries.DapperSqlHelper" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.SqlBuilder" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.DependencyInjection" />
    <PackageReference Include="UnitsNet" />
    <PackageReference Include="Riok.Mapperly" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="sql/**/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\NZWalks.Core.csproj" />
  </ItemGroup>
</Project>
